import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import "./globals.css";

const kumhSans = Kumbh_Sans({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kumhSans.className} ${kumhSans.className} antialiased`}>
        <div className="px-[200px] max-[1443px]:px-20 max-[1200px]:px-10 max-[1112px]:px-0 max-[1032px]:text-[12px] transition-all duration-300">{children}</div>
      </body>
    </html>
  );
}
