import type { Metadata } from "next";
import { Inter, IBM_Plex_Sans_Thai, Kumbh_Sans } from "next/font/google";
import "./globals.css";

const kumhSans = Kumbh_Sans({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kumhSans.className} ${kumhSans.className} antialiased`}>
        <div className="px-60">{children}</div>
      </body>
    </html>
  );
}
